/**
 * Web app manifest — enables "Add to home screen" / "Install" prompts.
 *
 * Hebrew-default + RTL since both kids and the parent's primary surface
 * is Hebrew. start_url points at /he so the launched PWA lands at the
 * locale-aware kid home / login.
 *
 * Theme + background pulled from BRANDBOOK §2.2:
 *   --bg     = #FAF8F5 (cream — what the PWA splash screen shows)
 *   --pink   = #E94B7F (pink-dark — what the OS status bar tints)
 *
 * Icons are code-generated by Next 16's metadata API (see icon.tsx and
 * apple-icon.tsx). Browsers fetch them at hashed URLs Next emits, so we
 * don't need static PNG files in /public.
 */

import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Reco',
    short_name: 'Reco',
    description: 'Reco — kids earn coins for everyday wins.',
    start_url: '/he',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#FAF8F5',
    theme_color: '#E94B7F',
    dir: 'rtl',
    lang: 'he',
    icons: [
      // The two PNGs Next.js generates from icon.tsx / icon0.tsx via
      // ImageResponse. Hash suffixes are added at build time so cache-
      // busting works automatically; the path before the hash is stable.
      {
        src: '/icon0',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon1',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon1',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
