/**
 * Web app manifest — enables "Add to home screen" / "Install" prompts.
 *
 * Hebrew-default + RTL since both kids and the parent's primary surface
 * is Hebrew. start_url points at /he so the launched PWA lands at the
 * locale-aware kid home / login.
 *
 * Theme + background pulled from BRANDBOOK §2.2:
 *   --bg     = #FAF8F5 (cream — what the PWA splash screen shows)
 *   --pink   = #E94B7F (pink-dark — what the OS status bar tints)
 *
 * Icons are code-generated by Next 16's metadata API (see icon.tsx and
 * apple-icon.tsx). Browsers fetch them at hashed URLs Next emits, so we
 * don't need static PNG files in /public.
 */

import type { MetadataRoute } from 'next';
import { cookies } from 'next/headers';
import { ACTIVE_THEME_COOKIE } from '../lib/admin-theme/constants';
import { asTheme, themeStatusBar } from '../lib/theme';

export default async function manifest(): Promise<MetadataRoute.Manifest> {
  // The PWA install caches the manifest's theme_color and uses it as the
  // launcher / splash background tint. Reading the active-theme cookie at
  // request time so a kid who already picked ocean gets the right colour
  // baked into their installed PWA — otherwise the OS chrome above the
  // page paints in the bubblegum default and looks wrong forever.
  const jar = await cookies();
  const themeId = asTheme(jar.get(ACTIVE_THEME_COOKIE)?.value);
  const themeColor = themeStatusBar(themeId);

  return {
    name: 'Trophy',
    short_name: 'Trophy',
    description: 'Trophy — kids earn coins for everyday wins.',
    start_url: '/he',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#FAF8F5',
    theme_color: themeColor,
    dir: 'rtl',
    lang: 'he',
    icons: [
      // The two PNGs Next.js generates from icon.tsx / icon0.tsx via
      // ImageResponse. Hash suffixes are added at build time so cache-
      // busting works automatically; the path before the hash is stable.
      {
        src: '/icon0',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon1',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon1',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
