/**
 * Reco — Design Tokens as CSS Variables.
 *
 * Generates a CSS string with `:root { ... }` containing every token from
 * tokens.ts as a CSS custom property. Inject this into `globals.css` so all
 * component styles (Tailwind utility classes via [var(--token)], inline styles)
 * can reference them.
 *
 * Usage:
 *   // apps/web/src/app/globals.css
 *   @import url('./reco-tokens.css');  // run scripts/generate-tokens-css.mjs to materialize
 *
 * OR (preferred) inline in globals.css using the string export at build time.
 */

import { colors, fontSizes, lineHeights, radii, shadows, motion, spacing } from './tokens';

/**
 * Generates the full `:root { ... }` CSS variables block.
 * Call this at build time from a script that writes to apps/web/src/app/reco-tokens.css.
 */
export function generateCssVariables(): string {
  const lines: string[] = [];

  lines.push('/*');
  lines.push(' * Reco — Design Tokens · auto-generated from packages/shared/src/design-tokens/');
  lines.push(' * DO NOT EDIT THIS FILE BY HAND. Edit tokens.ts and re-run generation.');
  lines.push(' */');
  lines.push('');
  lines.push(':root {');

  lines.push('  /* Colors */');
  for (const [key, value] of Object.entries(colors)) {
    lines.push(`  --${kebab(key)}: ${value};`);
  }

  lines.push('');
  lines.push('  /* Font sizes */');
  for (const [key, value] of Object.entries(fontSizes)) {
    lines.push(`  --fs-${kebab(key)}: ${value};`);
  }

  lines.push('');
  lines.push('  /* Line heights */');
  for (const [key, value] of Object.entries(lineHeights)) {
    lines.push(`  --lh-${kebab(key)}: ${value};`);
  }

  lines.push('');
  lines.push('  /* Border radii */');
  for (const [key, value] of Object.entries(radii)) {
    lines.push(`  --radius-${kebab(key)}: ${value};`);
  }

  lines.push('');
  lines.push('  /* Shadows */');
  for (const [key, value] of Object.entries(shadows)) {
    lines.push(`  --shadow-${kebab(key)}: ${value};`);
  }

  lines.push('');
  lines.push('  /* Motion */');
  for (const [key, value] of Object.entries(motion)) {
    lines.push(`  --motion-${kebab(key)}: ${value};`);
  }

  lines.push('');
  lines.push('  /* Spacing (selected) */');
  for (const [key, value] of Object.entries(spacing)) {
    lines.push(`  --space-${key.replace('.', '-')}: ${value};`);
  }

  lines.push('}');

  return lines.join('\n');
}

function kebab(camel: string): string {
  return camel.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
